import os
import joblib
import httpx
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, field_validator
from sklearn.pipeline import Pipeline
from contextlib import asynccontextmanager
from dotenv import load_dotenv
import shap

# ─── GEMINI CONFIG ────────────────────────────────────────────────────────────

load_dotenv(override=True)
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models"

# Fallback chain: if one hits rate limit, try the next
GEMINI_MODELS = [
    "gemini-3.1-flash-lite",
    "gemini-2.5-flash",
    "gemini-2.0-flash",
    "gemini-1.5-flash",
]

# ─── MODEL LOADING ────────────────────────────────────────────────────────────

MODEL_DIR = os.path.join(os.path.dirname(__file__), "model")

models = {
    "rf_model":     None,
    "scaler":       None,
    "le_soil":      None,
    "le_crop":      None,
    "le_target":    None,
    "column_names": None,
    "pipeline":     None,
    "explainer":    None,
}

@asynccontextmanager
async def lifespan(app: FastAPI):
    models["rf_model"]     = joblib.load(os.path.join(MODEL_DIR, "rf_model.pkl"))
    models["scaler"]       = joblib.load(os.path.join(MODEL_DIR, "scaler.pkl"))
    models["le_soil"]      = joblib.load(os.path.join(MODEL_DIR, "le_soil.pkl"))
    models["le_crop"]      = joblib.load(os.path.join(MODEL_DIR, "le_crop.pkl"))
    models["le_target"]    = joblib.load(os.path.join(MODEL_DIR, "le_target.pkl"))
    models["column_names"] = joblib.load(os.path.join(MODEL_DIR, "column_names.pkl"))
    models["pipeline"]     = Pipeline([("scaler", models["scaler"]), ("rf_model", models["rf_model"])])
    models["explainer"]    = shap.TreeExplainer(models["rf_model"])
    print("Model artifacts and SHAP explainer loaded successfully.")
    yield

# ─── APP SETUP ────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Smart Fertilizer Recommendation API",
    description=(
        "Predicts the best fertilizer for a given set of soil, crop, "
        "and environmental conditions using a trained Random Forest classifier. "
        "Returns SHAP-based explanations for every prediction."
    ),
    version="2.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── SCHEMAS ──────────────────────────────────────────────────────────────────

class FertilizerRequest(BaseModel):
    Temparature: float = Field(..., example=26.0,  description="Temperature in °C")
    Humidity:    float = Field(..., example=52.0,  description="Relative humidity (%)")
    Moisture:    float = Field(..., example=38.0,  description="Soil moisture (%)")
    Soil_Type:   str   = Field(..., alias="Soil Type", example="Loamy",
                               description="Soil type string (e.g. Loamy, Sandy, Clayey)")
    Crop_Type:   str   = Field(..., alias="Crop Type", example="Wheat",
                               description="Crop type string (e.g. Wheat, Maize, Sugarcane)")
    Nitrogen:    float = Field(..., example=37.0,  description="Soil nitrogen (kg/ha)")
    Potassium:   float = Field(..., example=0.0,   description="Soil potassium (kg/ha)")
    Phosphorous: float = Field(..., example=0.0,   description="Soil phosphorous (kg/ha)")

    model_config = {"populate_by_name": True}

    @field_validator("Temparature", "Humidity", "Moisture",
                     "Nitrogen", "Potassium", "Phosphorous")
    @classmethod
    def must_be_non_negative(cls, v):
        if v < 0:
            raise ValueError("Value must be non-negative")
        return v


class FeatureContribution(BaseModel):
    feature:    str   = Field(description="Feature name")
    value:      float = Field(description="Actual input value for this feature")
    shap_value: float = Field(description="SHAP value: magnitude and direction of impact")
    direction:  str   = Field(description="'increases' or 'decreases' the prediction confidence")
    impact:     str   = Field(description="'high', 'medium', or 'low' relative impact")


class SHAPExplanation(BaseModel):
    predicted_class:  str   = Field(description="The fertilizer being explained")
    base_value:       float = Field(description="Model baseline confidence before any features")
    final_confidence: float = Field(description="Final predicted confidence for this class")
    top_features:     list[FeatureContribution] = Field(
                          description="Top features ranked by absolute SHAP impact"
                      )


class FertilizerResponse(BaseModel):
    predicted_fertilizer: str
    confidence:           float
    explanation:          str = Field(description="Plain-language explanation generated by Gemini")


# ─── HELPERS ──────────────────────────────────────────────────────────────────

FEATURE_META = {
    "Temparature": ("Temperature",     "°C",    "air/soil temperature"),
    "Humidity":    ("Humidity",        "%",     "relative air humidity"),
    "Moisture":    ("Soil Moisture",   "%",     "water content in the soil"),
    "Soil Type":   ("Soil Type",       "",      "type of soil"),
    "Crop Type":   ("Crop Type",       "",      "crop being grown"),
    "Nitrogen":    ("Nitrogen (N)",    "kg/ha", "nitrogen nutrients in the soil"),
    "Potassium":   ("Potassium (K)",   "kg/ha", "potassium nutrients in the soil"),
    "Phosphorous": ("Phosphorous (P)", "kg/ha", "phosphorous nutrients in the soil"),
}

def classify_impact(shap_val: float, max_abs: float) -> str:
    ratio = abs(shap_val) / max_abs if max_abs > 0 else 0
    if ratio >= 0.5: return "high"
    if ratio >= 0.2: return "medium"
    return "low"


def compute_shap_explanation(
    input_df: pd.DataFrame,
    class_idx: int,
    predicted_fertilizer: str,
    confidence: float,
    original_values: dict,
) -> SHAPExplanation:
    scaler       = models["scaler"]
    column_names = models["column_names"]
    explainer    = models["explainer"]

    scaled_df   = pd.DataFrame(scaler.transform(input_df), columns=column_names)
    shap_values = explainer.shap_values(scaled_df)

    sample_shap = (
        shap_values[class_idx][0]
        if isinstance(shap_values, list)
        else shap_values[0, :, class_idx]
    )

    expected_val = (
        float(explainer.expected_value[class_idx])
        if isinstance(explainer.expected_value, (list, np.ndarray))
        else float(explainer.expected_value)
    )

    max_abs = float(np.max(np.abs(sample_shap))) if len(sample_shap) > 0 else 1.0

    contributions = [
        FeatureContribution(
            feature    = feat,
            value      = round(float(original_values.get(feat, 0.0)), 4),
            shap_value = round(float(sv), 6),
            direction  = "increases" if sv >= 0 else "decreases",
            impact     = classify_impact(sv, max_abs),
        )
        for feat, sv in zip(column_names, sample_shap)
    ]
    contributions.sort(key=lambda x: abs(x.shap_value), reverse=True)

    return SHAPExplanation(
        predicted_class  = predicted_fertilizer,
        base_value       = round(expected_val, 6),
        final_confidence = round(confidence, 4),
        top_features     = contributions,
    )


def build_local_explanation(
    fertilizer: str,
    crop_type: str,
    soil_type: str,
    shap_explanation: SHAPExplanation,
) -> str:
    """Farmer-friendly fallback explanation when all Gemini models are unavailable."""
    FEATURE_REASONS = {
        "Nitrogen":    "Nitrogen is the main nutrient that helps plants grow green and strong.",
        "Potassium":   "Potassium helps roots grow and keeps your plants healthy.",
        "Phosphorous": "Phosphorous gives plants the energy they need to flower and produce.",
        "Moisture":    "Soil moisture tells us how much water is currently in your soil.",
        "Temparature": "Temperature affects how fast your plants can absorb nutrients.",
        "Humidity":    "Humidity affects how quickly fertilizer dissolves and reaches the roots.",
        "Soil Type":   "Your soil type affects how well it holds and releases nutrients.",
        "Crop Type":   "Different crops have different nutrient needs.",
    }

    summary = [f"{fertilizer} is the right choice for your {crop_type} crop on {soil_type} soil."]

    for fc in shap_explanation.top_features[:4]:
        value  = fc.value if fc.feature not in ["Soil Type", "Crop Type"] else (soil_type if fc.feature == "Soil Type" else crop_type)
        pushed = "helped choose" if fc.direction == "increases" else "was also considered"
        reason = FEATURE_REASONS.get(fc.feature, f"{fc.feature} plays a role in fertilizer selection.")
        summary.append(f"{reason} Your reading of {value} {pushed} {fertilizer} for your field.")

    summary.append(f"Apply {fertilizer} evenly across your field and water it in well so the nutrients reach the roots.")
    return " ".join(summary)


async def get_gemini_explanation(
    fertilizer: str,
    confidence: float,
    shap_explanation: SHAPExplanation,
    crop_type: str,
    soil_type: str,
) -> str:
    """Try each Gemini model in order. If all fail, return a sorry message."""
    if not GEMINI_API_KEY:
        raise HTTPException(
            status_code=500,
            detail="GEMINI_API_KEY environment variable is not set.",
        )

    top_4         = shap_explanation.top_features[:4]
    shap_summary  = ", ".join([
        f"{FEATURE_META.get(fc.feature, (fc.feature,))[0]} ({'more' if fc.direction == 'increases' else 'less'} important)"
        for fc in top_4
    ])
    input_summary = ", ".join([
        f"{FEATURE_META.get(fc.feature, (fc.feature,))[0]}={fc.value}"
        for fc in top_4
    ])

    prompt = f"""You are a friendly agricultural advisor explaining a fertilizer recommendation to a farmer with no technical background.
The recommended fertilizer is '{fertilizer}' for a '{crop_type}' crop on '{soil_type}' soil.
The conditions are: {input_summary}.
The main factors behind this recommendation are: {shap_summary}.

Write a simple, friendly explanation (under 120 words) that answers: "Why is {fertilizer} the right choice for these conditions?"

Rules:
- Use plain everyday language. No jargon, no scientific terms.
- Focus on practical reasons a farmer would understand (e.g., "your soil is low on nitrogen, and this fertilizer will fix that quickly").
- If you must use a technical term, explain it right away in simple words.
- Do NOT mention SHAP values, numbers from the data, model, or AI — just explain the 'why' in plain words.
- Always say 'your soil', 'your crop', 'your field'.
- Keep a warm, helpful tone as if talking to a friend.
- Output plain text only. No bullet points, no headers, no markdown."""

    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.2, "maxOutputTokens": 1000},
    }

    async with httpx.AsyncClient(timeout=21.0) as client:
        for model in GEMINI_MODELS:
            url = f"{GEMINI_BASE_URL}/{model}:generateContent"
            try:
                resp = await client.post(url, params={"key": GEMINI_API_KEY}, json=payload)
            except httpx.HTTPError:
                continue  # network error → try next model

            if resp.status_code in (429, 500, 503):
                continue  # rate limit or server error → try next model

            if resp.status_code != 200:
                #print(f"{model} failed:", resp.status_code, resp.text)
                continue

            try:
                return resp.json()["candidates"][0]["content"]["parts"][0]["text"].strip()
            except (KeyError, IndexError, ValueError):
                continue  # malformed response → try next model

    # All models exhausted
    return "Sorry, explanation is not available right now."


# ─── ENDPOINTS ────────────────────────────────────────────────────────────────

@app.get("/", tags=["General"])
def root():
    return {
        "message": "Smart Fertilizer Recommendation API is running.",
        "docs":    "/docs",
    }


@app.get("/categories", tags=["General"])
def get_categories():
    """Return all valid string values for Soil Type and Crop Type."""
    if models["le_soil"] is None or models["le_crop"] is None:
        raise HTTPException(status_code=503, detail="Model not loaded yet.")
    return {
        "soil_types": list(models["le_soil"].classes_),
        "crop_types": list(models["le_crop"].classes_),
    }


@app.post("/predict", response_model=FertilizerResponse, tags=["Prediction"])
async def predict(request: FertilizerRequest):
    """
    Predict the best fertilizer and return a plain-language explanation
    describing which factors drove the recommendation and why.
    """
    if models["pipeline"] is None:
        raise HTTPException(status_code=503, detail="Model not loaded yet.")

    # ── Encode categoricals ──────────────────────────────────────────────────
    try:
        soil_encoded = int(models["le_soil"].transform([request.Soil_Type])[0])
    except ValueError:
        raise HTTPException(
            status_code=422,
            detail=f"Unknown Soil Type: '{request.Soil_Type}'. "
                   f"Valid options: {list(models['le_soil'].classes_)}"
        )
    try:
        crop_encoded = int(models["le_crop"].transform([request.Crop_Type])[0])
    except ValueError:
        raise HTTPException(
            status_code=422,
            detail=f"Unknown Crop Type: '{request.Crop_Type}'. "
                   f"Valid options: {list(models['le_crop'].classes_)}"
        )

    raw = {
        "Temparature": request.Temparature,
        "Humidity":    request.Humidity,
        "Moisture":    request.Moisture,
        "Soil Type":   soil_encoded,
        "Crop Type":   crop_encoded,
        "Nitrogen":    request.Nitrogen,
        "Potassium":   request.Potassium,
        "Phosphorous": request.Phosphorous,
    }

    try:
        input_df = pd.DataFrame([raw])[models["column_names"]]
    except KeyError as e:
        raise HTTPException(
            status_code=422,
            detail=f"Feature mismatch: {e}. Expected columns: {models['column_names']}"
        )

    # ── Predict ───────────────────────────────────────────────────────────────
    encoded_pred = models["pipeline"].predict(input_df)[0]
    proba        = models["pipeline"].predict_proba(input_df)[0]
    confidence   = round(float(proba[encoded_pred]), 4)
    fertilizer   = str(models["le_target"].inverse_transform([encoded_pred])[0])

    # ── SHAP explanation (internal) ───────────────────────────────────────────
    shap_explanation = compute_shap_explanation(
        input_df             = input_df,
        class_idx            = int(encoded_pred),
        predicted_fertilizer = fertilizer,
        confidence           = confidence,
        original_values      = raw,
    )

    # ── Gemini plain-language explanation ─────────────────────────────────────
    gemini_text = await get_gemini_explanation(
        fertilizer       = fertilizer,
        confidence       = confidence,
        shap_explanation = shap_explanation,
        crop_type        = request.Crop_Type,
        soil_type        = request.Soil_Type,
    )

    return FertilizerResponse(
        predicted_fertilizer = fertilizer,
        confidence           = confidence,
        explanation          = gemini_text,
    )